import os, random, time
from art import logo
from random import randint

attempts = 0
level = str(input("Pick a level. Type 'easy' or 'hard': ").lower())
comp_choice = random.randint(1, 100)
player_choice = int(input('Select a number: '))

# Prompts the user to type the level accurately
while (level != 'easy') and (level != 'hard'):
    print("Invalid input. Try again")
    level = str(input("Pick a level. Type 'easy' or 'hard': ").lower())
    if (level == 'easy') or (level == 'hard'):
        break

def scale(player_choice, comp_choice):
    """Compares the player's guess with the computer's chosen number.

    Args:
        player_choice (int): Number guessed by the player.
        comp_choice (int): Number the computer selected to be guessed.

    Returns:
        str: A message indicating whether the guess is too high, too low, or correct.
    """
    if (player_choice in range(1,101)) and (comp_choice in range(1,101)):
        if player_choice == comp_choice:
            print (f'CONGRATULATIONS! You guessed {comp_choice} correct!')
        elif player_choice < comp_choice:
            print ('Too low!')
        else:
            print ('Too high!')
    else:
        print("Invalid choice! Number out of range.")

if level == 'easy':
    attempts = 10
    print(f"\t\t\tEasy level. \n\tYou have {attempts} attempts to guess the correcct number.\n\t\t\tALL THE BEST!")
    scale(player_choice, comp_choice)
else:
    attempts = 5
    print(f"\t\t\tHard level. \n\tYou have {attempts} attempts to guess the correct number.\n\t\t\tALL THE BEST!")
    scale(player_choice,comp_choice)


# scale(player_choice,comp_choice)

def try_again(player_choice, comp_choice):
    """Continuously prompts the player to guess a number until the correct guess is made
    or runs out of attempts.

    Args:
        player_choice (int): Number guessed by the player.
        comp_choice (_type_): Correct number generated by the computer.

    Returns:
        str: Correct for the correct guess, failed for failed attempts
    """

    while player_choice != comp_choice:
        attempts = attempts - 1
        print(f"You have {attempts} attempts left")
        try_again()
        if player_choice == comp_choice:
            print("Correct!")
            break

# print(f"Computer choice is {comp_choice}")
# print(f'Your choice is {player_choice}')




# def try_again(player_choice, comp_choice):
#     """Continuously prompts the player to guess a number until the correct guess is made
#     or runs out of attempts.

#     Args:
#         player_choice (int): Number guessed by the player.
#         comp_choice (_type_): Correct number generated by the computer.

#     Returns:
#         str: Correct for the correct guess, failed for failed attempts
#     """

#     while player_choice != comp_choice:
#         attempts = attempts - 1
#         print(f"You have {attempts} attempts left")
#         try_again()
#         if player_choice == comp_choice:
#             print("Correct!")
#             break